### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by IotaSpencer** [jeffrimko/Qprompt#1]
Considering this hasn't been pushed to within a month, I presume that the package is getting out of date, but there were a few things I wanted to ask.

* Are you working on a python3 version, or do you need help with that
* How well is this used by your own knowledge and with what

**Comment by jeffrimko** [comment]
Yes, this project is still being worked on. I have not started a Python 3 version yet; contributions are welcome!

As far as use, PyPI reports 684 downloads over the last month. Not sure how accurate that is.

**Comment by IotaSpencer** [comment]
I'm probably going to fork it and see about 2to3'ing this to see how well it transfers over, and see if anything else needs to be changed

**Comment by jeffrimko** [comment]
Okay, I have limited experience with Python 3 but my guess is this project will be pretty easy to port.

**Comment by jeffrimko** [comment]
Released `0.2.0` which should be Python 3 compatible.
