### ISSUE TITLE
Indentation error?

### ISSUE THREAD

**Issue by blancogr** [jeffrimko/Qprompt#12]
### Hello, 
when trying to run this simple script:
--------------------------------
import qprompt
qprompt.hrule(10)
--------------------------------

I get the following:
-------------------------------------------
Traceback (most recent call last):
  File "p.py", line 1, in <module>
    import qprompt
  File "<replaced my virtualenv path here>/python3.7/site-packages/qprompt.py", line 175
    self.add(*quit, func=lambda: quit[0])
    ^
IndentationError: unexpected indent
-------------------------------------------

Is this something I'm doing wrong?

**Comment by jeffrimko** [comment]
You are definitely not doing anything wrong, that should work.

I tried to recreate the issue on both Windows and Linux with Python 3.7 but didn't have any luck.

I'm guessing your local qprompt source file got modified somehow. Maybe try taking a look at the line specified in `qprompt.py` or send me your file if possible.

Assuming you installed qprompt with pip, it might be worth trying update with the command `pip install --upgrade qprompt` to see if that helps.

**Comment by jeffrimko** [comment]
Closing since there has been no response in two weeks. Guessing this was resolved by either updating or reinstalling qprompt via pip.
