### ISSUE TITLE
LICENSE in sdist

### ISSUE THREAD

**Issue by jayvdb** [jeffrimko/Qprompt#14]
It would be helpful for packaging if the sdist uploaded to PyPI included the `LICENSE` file.

This is now automatically done by recent setuptools, however the latest upload to PyPI doesnt include one.  Normally it could be explicitly added by listing it in `MANIFEST.in`, but you have a quite different layout in your repos so I dont how you would want to achieve this.

**Comment by jeffrimko** [comment]
I published a new release (`0.15.4`) which has the `LICENSE` file in the distribution. Try downloading it ([PyPI page](https://pypi.org/project/qprompt/)) and let me know if it looks okay.

**Comment by jayvdb** [comment]
Yup that looks good.

More contentious, is there any chance the sdist could also include the tests?

Then redistributors can run the tests from PyPI sdist, and therefore do not need to get the tests from [the github releases](https://github.com/jeffrimko/Qprompt/releases).

c.f. https://build.opensuse.org/package/show/home:jayvdb:py-new/python-qprompt

**Comment by jeffrimko** [comment]
I'm going to hold off on adding the tests to the package for now. Think that would require some restructuring or other way of handling expected paths. Might look into it but can't promise anything. Do you know of any reference projects that package up the tests?

**Comment by jayvdb** [comment]
Here is a set of packages that I have added tests to their sdist
https://github.com/search?q=author%3Ajayvdb+is%3Apr+is%3Amerged+MANIFEST.in

Not all of them are released yet, but most are, especially the older ones.  https://github.com/tox-dev/tox-travis/pull/121 is as good example as any, and is definitely visible in the released sdists since then.

**Comment by jeffrimko** [comment]
Sorry, haven't updated this in a while. Going to close for now since the `LICENSE` file has been added. Going to hold off on the tests.
