### ISSUE TITLE
Accessing selected menu item

### ISSUE THREAD

**Issue by thorstenkampe** [jeffrimko/Qprompt#3]
There seems to be a functional flaw in Qprompt menus: it returns the name - which is often unrelated to the actual value (description). See the following code:
```
import qprompt  # https://github.com/jeffrimko/Qprompt

menu = qprompt.Menu()
menu.add('1', 'Microsoft SQL Server')
menu.add('2', 'MySQL')
menu.add('3', 'Oracle')
menu.add('4', 'PostgreSQL')
menu.add('5', 'SQLite')

choice = menu.show()
```
`choice` would here a number between 1 and 5. How do I get to the database? I came up with `menu.entries[int(choice) - 1].desc` which is really cumbersome and only works because the names are numeric.

**Comment by jeffrimko** [comment]
Change the last line to `choice = menu.show(returns="desc")`. This will return the description associated with the chosen entry.

**Comment by jeffrimko** [comment]
Updated readme to include example of returning description. Closing this issue.
