### ISSUE TITLE
Help is confusing with validation

### ISSUE THREAD

**Issue by thorstenkampe** [jeffrimko/Qprompt#5]
See the following simple example:
```
>>> qprompt.ask_int('Port', vld = lambda n: 1 <= n <= 65535)
[?] Port: ?
[<function <lambda> at 0x000001704B7D5B70>]
[?] Port:
```

**Comment by jeffrimko** [comment]
For normal functions, it would be neat to display the docstring. For lambdas, might need to add a parameter to explicitly provide a help string.

**Comment by jeffrimko** [comment]
Closing since `ask` functions allow for additional `hlp/help` text to be supplied. For example:

`qprompt.ask_int('Port', vld = lambda n: 1 <= n <= 65535, help="Port number must be between 1-65535")`
