### ISSUE TITLE
Keywords dft and blk should be mutually exclusive

### ISSUE THREAD

**Issue by thorstenkampe** [jeffrimko/Qprompt#6]
See the following simple example:
```
>>> qprompt.ask_str(dft = 'abc', blk = True)
[?] Enter a string [abc]:
'abc'
>>> qprompt.ask_str(dft = 'abc')
[?] Enter a string [abc]:
'abc'
>>> qprompt.ask_str(blk = True)
[?] Enter a string:
''
```

**Comment by jeffrimko** [comment]
Good catch. This will be fixed in the next release.

**Comment by jeffrimko** [comment]
Closing since the behavior seems to be satisfactory: the `default` value is taken even if the `blank` flag is set. The docs mention that defaults will override the ability to supply blank input.
