### ISSUE TITLE
Keyword arguments are difficult to remember

### ISSUE THREAD

**Issue by thorstenkampe** [jeffrimko/Qprompt#7]
For the sake of brevity, keyword arguments have been shortened. Unfortunately they have become quite difficult to remember:
- dft (?)
- vld (?)
- shw (?)
- blk (black?, block?, bulk?)

**Comment by jeffrimko** [comment]
Been thinking about changing this. Will continue to support the short names but will also include keyword params for the full names. Will add in next release.

**Comment by jeffrimko** [comment]
Added full keywords in `0.9.4` for `ask` functions. They are not well documented yet so going to leave this issue open for now.

**Comment by jeffrimko** [comment]
Closing this since the feature has been previously added but the docs have now also been added in release `0.10.0`.
