### ISSUE TITLE
FeatureRequest: Default item for a menu

### ISSUE THREAD

**Issue by mungewell** [jeffrimko/Qprompt#9]
Can't figure out how to specify a default entry for a Menu (which will be selected if just enter is pressed). Guess it's not (yet) supported....

```
import qprompt

menu = qprompt.Menu(hdr="Fruit", msg="What's your favourite", returns="desc")
menu.add("1", "Apple")
menu.add("2", "Bananna")        # Make this the default
menu.add("3", "Carrot")

choice = menu.show()

print("I like %s too!" % choice)

qty = qprompt.ask_int(dft=1, msg="How many would you like")
print(qty)
```

**Comment by jeffrimko** [comment]
Correct, it is not yet supported. It's been on the [roadmap](https://github.com/jeffrimko/Qprompt#roadmap) for a while. Just haven't gotten around to implementing it yet. I will look into adding it soon and get back to you.

**Comment by jeffrimko** [comment]
Okay, [Qprompt `0.10.0`](https://pypi.org/project/qprompt/0.10.0/) now has this feature. Thanks!
